# Generated by Django 2.0.6 on 2018-12-01 19:06

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20181127_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2018/12/01')),
        ),
    ]
