# Generated by Django 2.0.6 on 2018-12-10 17:24

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20181201_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2018/12/10')),
        ),
    ]
