# Generated by Django 2.0.6 on 2018-12-12 20:18

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20181210_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2018/12/12')),
        ),
    ]
