# Generated by Django 2.0.6 on 2018-12-27 21:15

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20181212_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2018/12/27')),
        ),
    ]
