# Generated by Django 2.0.6 on 2019-01-01 18:04

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20181227_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2019/01/01')),
        ),
    ]
