# Generated by Django 2.0.6 on 2019-01-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20190101_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
