# Generated by Django 2.0.6 on 2019-01-17 22:53

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20190101_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2019/01/17')),
        ),
    ]
