# Generated by Django 2.0.6 on 2019-02-14 10:55

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20190117_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2019/02/14')),
        ),
    ]
