# Generated by Django 2.0.6 on 2019-04-25 03:07

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20190214_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='signale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2019/04/25')),
        ),
    ]
