# Generated by Django 2.0.6 on 2018-10-30 22:54

import SocialMedia.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionBenevole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisme', models.CharField(max_length=300)),
                ('nom_poste', models.CharField(max_length=300)),
                ('cause', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=6000)),
                ('date_commentaire', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireSignales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signale', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('id_chat', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Acceptée'), (2, 'Refusée'), (3, 'Bloquée')])),
            ],
        ),
        migrations.CreateModel(
            name='DemandeGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='SocialMedia/Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=300)),
                ('nom_poste', models.CharField(max_length=300)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actuel', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_formation', models.CharField(max_length=300)),
                ('nom_ecole', models.CharField(max_length=300)),
                ('domaine', models.CharField(blank=True, max_length=300, null=True)),
                ('activite_et_associations', models.TextField(blank=True, null=True)),
                ('annee_debut', models.DateField()),
                ('annee_fin', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateField()),
                ('statut_groupe', models.CharField(choices=[('publique', 'publique'), ('prive', 'privé')], max_length=255)),
                ('have_image', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LangueProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=6000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_image', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NiveauLangue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'statut'), (1, 'groupe'), (2, 'profil'), (3, 'offreEmploi'), (4, 'entreprise'), (5, 'demande')], null=True)),
                ('message', models.CharField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('date_notification', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pays', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=300)),
                ('diplome_requis', models.CharField(max_length=300)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD')], max_length=300)),
                ('description_poste', models.TextField()),
                ('profil_recherche', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('en_cours', models.BooleanField(default=True)),
                ('date_fin', models.DateField(blank=True, default=None, null=True)),
                ('type_emploi', models.CharField(choices=[('plein', 'Plein temps'), ('partiel', 'Temps partiel')], max_length=300)),
                ('nom_poste', models.CharField(max_length=300)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='SocialMedia/Image/')),
            ],
        ),
        migrations.CreateModel(
            name='PageEntreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_entreprise', models.CharField(max_length=3000, null=True)),
                ('siege_social', models.CharField(max_length=255, null=True)),
                ('annee_creation', models.IntegerField(null=True)),
                ('specialisation', models.CharField(max_length=255, null=True)),
                ('img_couverture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poste', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyContent', models.CharField(max_length=6000)),
                ('date_reply', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReplySignales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signale', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReseauSocialFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=SocialMedia.models.generate_path)),
                ('date_telechargement', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False)),
                ('original_statut_id', models.IntegerField(blank=True, null=True)),
                ('date_statut', models.DateTimeField()),
                ('contenu_statut', models.CharField(max_length=6000)),
                ('is_group_statut', models.BooleanField(default=False)),
                ('is_profil_statut', models.BooleanField(default=False)),
                ('shares_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatutSignales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signale', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Suivie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
