# Generated by Django 2.0.6 on 2018-10-30 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SocialMedia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivie',
            name='followed_profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='suivie',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiveur', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='statutsignales',
            name='signal_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='statutsignales',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Statut'),
        ),
        migrations.AddField(
            model_name='statut',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='files', to='SocialMedia.ReseauSocialFile'),
        ),
        migrations.AddField(
            model_name='statut',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='SocialMedia.ReseauSocialFile'),
        ),
        migrations.AddField(
            model_name='statut',
            name='likes',
            field=models.ManyToManyField(blank=True, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='statut',
            name='mur_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe'),
        ),
        migrations.AddField(
            model_name='statut',
            name='mur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_mur_profil', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='statut',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='statut',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos', to='SocialMedia.ReseauSocialFile'),
        ),
        migrations.AddField(
            model_name='reseausocialfile',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FileOwner', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='replysignales',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Reply'),
        ),
        migrations.AddField(
            model_name='replysignales',
            name='signal_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='reply',
            name='commentaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Commentaire'),
        ),
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ManyToManyField(blank=True, to='SocialMedia.ReseauSocialFile'),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likedBy', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='pageentreprise',
            name='abonnees',
            field=models.ManyToManyField(blank=True, related_name='abonnees', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='pageentreprise',
            name='administrateurs',
            field=models.ManyToManyField(blank=True, related_name='administrateurs', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='pageentreprise',
            name='entreprise',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Entreprise'),
        ),
        migrations.AddField(
            model_name='pageentreprise',
            name='moderateurs',
            field=models.ManyToManyField(blank=True, related_name='moderateurs', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='page_entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.PageEntreprise'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste_recherche', to='SocialMedia.Poste'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='profil_postulants',
            field=models.ManyToManyField(blank=True, related_name='profil_postulants', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='profil_publicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_publicateur', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='notification',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.PageEntreprise'),
        ),
        migrations.AddField(
            model_name='notification',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe'),
        ),
        migrations.AddField(
            model_name='notification',
            name='offreEmploi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.OffreEmploi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='notification',
            name='profil_to_notify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_to_notify', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='notification',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Statut'),
        ),
        migrations.AddField(
            model_name='messageconversation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Conversation'),
        ),
        migrations.AddField(
            model_name='messageconversation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Image'),
        ),
        migrations.AddField(
            model_name='messageconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='langueprofil',
            name='langue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Langue'),
        ),
        migrations.AddField(
            model_name='langueprofil',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.NiveauLangue'),
        ),
        migrations.AddField(
            model_name='langueprofil',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='adherents',
            field=models.ManyToManyField(related_name='adherent', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='admins',
            field=models.ManyToManyField(related_name='admin', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createur', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='moderators',
            field=models.ManyToManyField(related_name='moderateur', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='photo_couverture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_cover', to='main_app.Image'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='photo_profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_photo', to='main_app.Image'),
        ),
        migrations.AddField(
            model_name='formation',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Ecole'),
        ),
        migrations.AddField(
            model_name='formation',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='experience',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Entreprise'),
        ),
        migrations.AddField(
            model_name='experience',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Poste'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='demandegroupe',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='demandegroupe',
            name='groupe_recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe'),
        ),
        migrations.AddField(
            model_name='demandeami',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='demandeami',
            name='recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentairesignales',
            name='commentaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Commentaire'),
        ),
        migrations.AddField(
            model_name='commentairesignales',
            name='signal_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='image',
            field=models.ManyToManyField(blank=True, to='SocialMedia.ReseauSocialFile'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='likes',
            field=models.ManyToManyField(blank=True, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Statut'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='actionbenevole',
            name='organisme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Organisme'),
        ),
        migrations.AddField(
            model_name='actionbenevole',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Poste'),
        ),
        migrations.AddField(
            model_name='actionbenevole',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AlterUniqueTogether(
            name='suivie',
            unique_together={('follower', 'followed_profil')},
        ),
    ]
