# Generated by Django 2.0.6 on 2018-11-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_auto_20181030_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupe',
            options={'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
        migrations.AlterModelOptions(
            name='offreemploi',
            options={'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.AlterModelOptions(
            name='pageentreprise',
            options={'verbose_name': 'Page Entreprise', 'verbose_name_plural': 'Pages Entreprise'},
        ),
        migrations.AlterModelOptions(
            name='statut',
            options={'verbose_name': 'Statut', 'verbose_name_plural': 'Statuts'},
        ),
        migrations.AddField(
            model_name='groupe',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageentreprise',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statut',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
    ]
