# Generated by Django 2.0.6 on 2019-02-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profil_qa_view'),
        ('SocialMedia', '0004_auto_20190214_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractStatut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_statut', models.DateTimeField(auto_now_add=True)),
                ('contenu_statut', models.CharField(max_length=6000)),
                ('views_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('type_statut', models.CharField(choices=[('original', 'original'), ('shared', 'shared')], default='original', max_length=15)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.ReseauSocialFile')),
                ('likes', models.ManyToManyField(blank=True, to='main_app.Profil')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Commentaire')),
            ],
            options={
                'ordering': ['-date_commentaire'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireSignales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(default='', max_length=1000)),
                ('date_signale', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Commentaire')),
                ('signal_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='StatutSignales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(default='', max_length=1000)),
                ('type', models.CharField(default='original', max_length=15)),
                ('date_signale', models.DateTimeField(auto_now_add=True)),
                ('signal_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='SharedStatut',
            fields=[
                ('abstractstatut_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SocialMedia.AbstractStatut')),
                ('date_share', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('SocialMedia.abstractstatut',),
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('abstractstatut_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SocialMedia.AbstractStatut')),
                ('is_group_statut', models.BooleanField(default=False)),
                ('is_profil_statut', models.BooleanField(default=False)),
                ('is_entreprise_statut', models.BooleanField(default=False)),
                ('is_link_statut', models.BooleanField(default=False)),
                ('link_icon', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('link_title', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('link_description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('link_url', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('files', models.ManyToManyField(blank=True, related_name='files', to='SocialMedia.ReseauSocialFile')),
                ('images', models.ManyToManyField(blank=True, related_name='images', to='SocialMedia.ReseauSocialFile')),
                ('mur_entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_mur_entreprise', to='SocialMedia.PageEntreprise')),
                ('mur_groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_mur_groupe', to='SocialMedia.Groupe')),
                ('videos', models.ManyToManyField(blank=True, related_name='videos', to='SocialMedia.ReseauSocialFile')),
            ],
            options={
                'verbose_name': 'Statut',
                'verbose_name_plural': 'Statuts',
            },
            bases=('SocialMedia.abstractstatut',),
        ),
        migrations.AddField(
            model_name='statutsignales',
            name='statut_signale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statut_signales', to='SocialMedia.AbstractStatut'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.AbstractStatut'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='abstractstatut',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='profil_likes_statut', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='abstractstatut',
            name='mur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_mur_profil', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='abstractstatut',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_statut', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='sharedstatut',
            name='shared_statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_statut', to='SocialMedia.Statut'),
        ),
    ]
