# Generated by Django 2.0.6 on 2019-04-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0005_auto_20190214_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentairesignales',
            options={'ordering': ['-date_signale']},
        ),
        migrations.AlterModelOptions(
            name='sharedstatut',
            options={'verbose_name': 'Statut partagé', 'verbose_name_plural': 'Statut partagé'},
        ),
        migrations.AlterModelOptions(
            name='statutsignales',
            options={'ordering': ['-date_signale']},
        ),
        migrations.AddField(
            model_name='commentairesignales',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Statut'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statutsignales',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='abstractstatut',
            name='contenu_statut',
            field=models.CharField(default='', max_length=6000),
        ),
        migrations.AlterField(
            model_name='abstractstatut',
            name='mur_profil',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_mur_profil', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='abstractstatut',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_statut', to='main_app.Profil'),
        ),
    ]
