# Generated by Django 2.0.6 on 2018-12-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0002_auto_20181127_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='AO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('date_limit', models.DateTimeField()),
                ('time_limit', models.IntegerField(null=True)),
                ('contact_mail', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AOContacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('ao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.AO')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='AOSaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('ao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.AO')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='AOUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=60)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=255)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50, null=True)),
                ('codePostal', models.IntegerField(null=True)),
                ('telephone', models.CharField(max_length=30, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('trade_registry', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('facebook', models.URLField(blank=True, default='#', max_length=50)),
                ('linkedIn', models.URLField(blank=True, default='#', max_length=50)),
                ('twitter', models.URLField(blank=True, default='#', max_length=50)),
                ('github', models.URLField(blank=True, default='#', max_length=50)),
                ('youtube', models.URLField(blank=True, default='#', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('budget', models.CharField(max_length=10)),
                ('days', models.IntegerField()),
                ('message', models.TextField()),
                ('file', models.FileField(null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('ao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ao.AO')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('prod_date', models.IntegerField()),
                ('price', models.FloatField()),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ao.File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.AOUser')),
            ],
        ),
        migrations.CreateModel(
            name='PContacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('budget', models.FloatField(null=True)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.AO')),
            ],
        ),
        migrations.CreateModel(
            name='PSaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('budget', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('tva', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.AO')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.Company')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('unit', models.TextField(max_length=50)),
                ('price', models.FloatField()),
                ('qte', models.IntegerField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.Quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.Company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.Category')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(to='ao.SubCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.ManyToManyField(to='ao.City'),
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(to='ao.FileProject'),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(to='ao.Keyword'),
        ),
        migrations.AddField(
            model_name='pcontacted',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.Project'),
        ),
        migrations.AddField(
            model_name='pcontacted',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ao.Project'),
        ),
        migrations.AddField(
            model_name='aouser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.Company'),
        ),
        migrations.AddField(
            model_name='aouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='ao',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.Category'),
        ),
        migrations.AddField(
            model_name='ao',
            name='files',
            field=models.ManyToManyField(to='ao.File'),
        ),
        migrations.AddField(
            model_name='ao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
    ]
