# Generated by Django 2.0.6 on 2018-12-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profil_qa_view'),
        ('ao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationNbRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_rows', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.IntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='ao',
            name='blacklisted_companies',
            field=models.ManyToManyField(related_name='blacklisted_companies_ao', to='ao.Company'),
        ),
        migrations.AddField(
            model_name='ao',
            name='blacklisted_users',
            field=models.ManyToManyField(related_name='blacklisted_users_ao', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='ao',
            name='cloturee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ao',
            name='downloaded_piecejointe_companies',
            field=models.ManyToManyField(related_name='downloaded_piecejointe_companies_ao', to='ao.Company'),
        ),
        migrations.AddField(
            model_name='ao',
            name='downloaded_piecejointe_users',
            field=models.ManyToManyField(related_name='downloaded_piecejointe_users_ao', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='project',
            name='blacklisted_companies',
            field=models.ManyToManyField(related_name='blacklisted_companies_project', to='ao.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='blacklisted_users',
            field=models.ManyToManyField(related_name='blacklisted_users_project', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='project',
            name='downloaded_piecejointe_companies',
            field=models.ManyToManyField(related_name='downloaded_piecejointe_companies_project', to='ao.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='downloaded_piecejointe_users',
            field=models.ManyToManyField(related_name='downloaded_piecejointe_users_project', to='main_app.Profil'),
        ),
    ]
