# Generated by Django 2.0.6 on 2019-01-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0002_auto_20181227_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ao',
            options={'verbose_name': "Appel d'offre", 'verbose_name_plural': "Appels  d'offres"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Lot', 'verbose_name_plural': 'Lots'},
        ),
    ]
