# Generated by Django 2.0.6 on 2018-09-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, null=True, unique=True)),
                ('activite', models.CharField(max_length=255, null=True)),
                ('secteurActivite', models.CharField(choices=[('Publique', 'Publique'), ('Prive', 'Privé')], max_length=255, null=True)),
                ('capitale', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pays', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(max_length=255, null=True)),
                ('codePostal', models.IntegerField(null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('typeEntreprise', models.CharField(choices=[('Petite entreprise', 'Petite entreprise'), ('Grande entreprise', 'Grande entreprise'), ('Très petite entreprise', 'Très petite entreprise'), ('Moyenne entreprise', 'Moyenne entreprise')], max_length=255)),
                ('raison_social', models.CharField(max_length=255, null=True)),
                ('registre_commerce', models.CharField(max_length=255, null=True)),
                ('fax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('email_entreprise', models.EmailField(max_length=254, null=True)),
                ('adresse_Entreprise', models.CharField(max_length=255, null=True)),
                ('logo', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetterMails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('tel', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('tel_portable', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('telecopie', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('ville', models.CharField(default='', max_length=300)),
                ('pays', models.CharField(default='', max_length=300)),
                ('token_email', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('token_email_expiration', models.DateTimeField(blank=True, null=True)),
                ('civilite', models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], max_length=255)),
                ('code_postal', models.CharField(max_length=255)),
                ('adresse_profile', models.CharField(max_length=255)),
                ('adresse_profile2', models.CharField(blank=True, max_length=255, null=True)),
                ('is_first_appoffre', models.BooleanField(default=True)),
                ('resume', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('is_professional', models.BooleanField(default=False)),
                ('is_journaliste', models.BooleanField(default=False)),
                ('is_etudiant', models.BooleanField(default=False)),
                ('is_particulier', models.BooleanField(default=False)),
                ('is_active_professional', models.BooleanField(default=False, verbose_name="Compte Activé par l'administration")),
                ('is_supplier', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('connecte', models.IntegerField(blank=True, default=0, null=True)),
                ('fonction', models.CharField(blank=True, choices=[('Privé', 'Au secteur privé'), ('Public', 'Au secteur public')], default='', max_length=300, null=True)),
                ('service', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('activite', models.CharField(blank=True, choices=[('Administration publique', 'Administration publique'), ('Architecture', 'Architecture'), ('Association, organisme professionnel', 'Association, organisme professionnel'), ('Bâtiment', 'Bâtiment'), ('Aménagement urbain', 'Aménagement urbain'), ('Collectivités locales - territoriales', 'Collectivités locales - territoriales'), ('Commerce - Grande distribution', 'Commerce - Grande distribution'), ('Communication - Edition', 'Communication - Edition'), ('Conseil - Etudes - Ingénierie', 'Conseil - Etudes - Ingénierie'), ('Contrôle technique', 'Contrôle technique'), ('Education - Formation', 'Education - Formation'), ('Energie', 'Energie'), ('Environnement - Développement durable', 'Environnement - Développement durable'), ('Finance - Banque - Assurance', 'Finance - Banque - Assurance'), ('Hôtellerie - Restauration - Tourisme', 'Hôtellerie - Restauration - Tourisme'), ('Immobilier', 'Immobilier'), ('Informatique - Télécommunications', 'Informatique - Télécommunications'), ('Juridique', 'Juridique'), ('Matériaux', 'Matériaux'), ('Matériel, outillage et procédés', 'Matériel, outillage et procédés'), ('Mobilier et décoration', 'Mobilier et décoration'), ('Recherche (Organisme - Laboratoire)', 'Recherche (Organisme - Laboratoire)'), ('Transport - Logistique', 'Transport - Logistique'), ('Travaux spéciaux', 'Travaux spéciaux'), ('Autres', 'Autres')], default='', max_length=300, null=True)),
                ('taille_entreprise', models.CharField(blank=True, choices=[('1 à 10 salariés', '1 à 10 salariés'), ('11 à 20 salariés', '11 à 20 salariés'), ('21 à 50 salariés', '21 à 50 salariés'), ('51 à 249 salariés', '51 à 249 salariés'), ('250 à 500 salariés', '250 à 500 salariés'), ('501 à 1 000 salariés', '501 à 1 000 salariés'), ('Plus de 1 000 salariés', 'Plus de 1 000 salariés')], default='', max_length=300, null=True)),
                ('departement', models.CharField(blank=True, choices=[('Achat', 'Achat'), ('Commercial', 'Commercial'), ('Communication, Evénementiel', 'Communication, Evénementiel'), ('Construction, Immobilier, Infrastrcutures', 'Construction, Immobilier, Infrastrcutures'), ('Développement durable', 'Développement durable'), ('Développement économique', 'Développement économique'), ('Eaux', 'Eaux'), ('Environnement', 'Environnement'), ('Espaces verts, Biodiversité', 'Espaces verts, Biodiversité'), ('Etude', 'Etude'), ('Exploitation', 'Exploitation'), ('Export - Import', 'Export - Import'), ('Finance', 'Finance'), ('Hygiène - Sécurité', 'Hygiène - Sécurité'), ('Informatique', 'Informatique'), ('Juridique', 'Juridique'), ('Logistique - transport', 'Logistique - transport'), ('Maintenance', 'Maintenance'), ('Qualité, méthodes', 'Qualité, méthodes'), ('Recherche & Développement', 'Recherche & Développement'), ('Ressources humaines', 'Ressources humaines'), ('Restauration', 'Restauration'), ('Santé, Affaires sociales', 'Santé, Affaires sociales'), ('Service Technique', 'Service Technique'), ('Services généraux', 'Services généraux'), ('Technique - Production', 'Technique - Production'), ('Transports urbains', 'Transports urbains'), ('Usine - Site', 'Usine - Site'), ('Autre', 'Autre')], default='', max_length=300, null=True)),
                ('nom_entreprise', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('raison_sociale', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Raison Social')),
                ('tel_fixe', models.CharField(default='', max_length=255, verbose_name='Téléphone Fixe')),
                ('university', models.CharField(default='', max_length=255, verbose_name='Etablissement universitaire')),
                ('level_of_education', models.CharField(default='', max_length=255, verbose_name='Niveau de formation')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Entreprise')),
                ('experience_profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_profil', to='SocialMedia.Experience')),
                ('formation_profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formation_profil', to='SocialMedia.Formation')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEntreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('publique', 'publique'), ('prive', 'prive')], max_length=255)),
            ],
        ),
    ]
