# Generated by Django 2.0.6 on 2018-10-30 22:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ecommerce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=254)),
                ('post_code', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=254)),
                ('region', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=ecommerce.models.PathAndRename('images/2018/10/30'))),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code_hex', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommerceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=ecommerce.models.PathAndRename('images/2018/10/30'))),
            ],
        ),
        migrations.CreateModel(
            name='CommerceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ecommerce.models.PathAndRename('images/2018/10/30'))),
            ],
        ),
        migrations.CreateModel(
            name='CommerceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='detail', max_length=250)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommerceRatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommerceSCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommerceSCategoryOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CommerceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceSCategoryTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CommerceSCategoryOne')),
            ],
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Created', max_length=200)),
                ('payment_method', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paypal', 'Paypal')], default='Cash On Delivery', max_length=20)),
                ('delivery_method', models.CharField(choices=[('Free Shipping', 'Free Shipping'), ('Flat Shipping Rate', 'Flat Shipping Rate')], default='Free Shipping', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('track_number', models.CharField(blank=True, max_length=300, null=True)),
                ('date_payment', models.DateField(blank=True, null=True)),
                ('date_complete', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Color')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('image', models.ImageField(upload_to=ecommerce.models.PathAndRename('images/2018/10/30'))),
                ('date_add', models.DateField(auto_now_add=True)),
                ('number_views', models.IntegerField(default=0)),
                ('quantity_min', models.IntegerField(blank=True, default=1, null=True)),
                ('unit', models.CharField(default='Piece', max_length=200)),
                ('is_pro', models.BooleanField(default=False)),
                ('packaging_detail', models.CharField(blank=True, max_length=1000, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', ckeditor.fields.RichTextField(default=' ')),
                ('price_from', models.BooleanField(default=False)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('active', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('accessories', models.ManyToManyField(blank=True, related_name='_product_accessories_+', to='ecommerce.Product')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Brand')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CommerceSCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_daily', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_profile', models.ImageField(upload_to=ecommerce.models.PathAndRename('images/2018/10/30'))),
                ('image_cover', models.ImageField(upload_to=ecommerce.models.PathAndRename('images/2018/10/30'))),
                ('description', models.TextField(blank=True, null=True)),
                ('number_visitors', models.IntegerField(default=0)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('tel', models.CharField(max_length=30, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, to='ecommerce.CommerceSCategoryOne')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ecommerce.models.PathAndRename('slides/2018/10/30'))),
                ('date_add', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('first_quantity', models.IntegerField(default=0)),
                ('price_sup', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
            bases=('ecommerce.address',),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
            bases=('ecommerce.address',),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ecommerce.Tag'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='messagesupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Shop'),
        ),
        migrations.AddField(
            model_name='description',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='compare',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='compare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='commercescategory',
            name='category_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CommerceSCategoryTwo'),
        ),
        migrations.AddField(
            model_name='commerceratting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='commerceinformation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='commerceimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Color'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
    ]
