# Generated by Django 2.0.6 on 2018-10-30 22:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=2555)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('date_creation', models.DateField()),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Compagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('emails_ouverts', models.IntegerField(default=0)),
                ('envoyee', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=None, null=True)),
                ('contenu_email', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('emails', models.ManyToManyField(to='main_app.NewsLetterMails')),
                ('lanceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeDroit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='droit',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.GroupeDroit'),
        ),
        migrations.AddField(
            model_name='admin',
            name='droits',
            field=models.ManyToManyField(to='dashboard.Droit'),
        ),
        migrations.AddField(
            model_name='action',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Admin'),
        ),
    ]
