# Generated by Django 2.0.6 on 2019-01-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.BooleanField(default=False)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=300)),
                ('email_host_user', models.CharField(default='', max_length=300)),
                ('email_host_password', models.CharField(default='', max_length=300)),
                ('email_port', models.CharField(default='587', max_length=300)),
            ],
        ),
    ]
