# Generated by Django 2.0.6 on 2019-04-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='titre_site',
            field=models.CharField(default='Ecosysteme BTP', max_length=300),
        ),
    ]
