# Generated by Django 2.0.6 on 2018-11-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'QA Article', 'verbose_name_plural': 'QA Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'QA Catégorie', 'verbose_name_plural': 'QA Catégories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'QA Tag', 'verbose_name_plural': 'QA Tags'},
        ),
    ]
