# Generated by Django 2.0.6 on 2018-11-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.AddField(
            model_name='profil',
            name='socialmedia_profil_views_number',
            field=models.IntegerField(default=0),
        ),
    ]
