# Generated by Django 2.0.6 on 2018-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181127_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='qa_view',
            field=models.IntegerField(default=0),
        ),
    ]
