# Generated by Django 2.0.6 on 2019-04-25 03:07

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profil_qa_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='cv',
            field=models.FileField(default='', upload_to=main_app.models.PathAndRename('CV')),
        ),
        migrations.AddField(
            model_name='profil',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='request_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='teacher_title',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='view_teacher',
            field=models.IntegerField(default=1),
        ),
    ]
