"""
Django settings for SocialNetworkJob project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c5$h8mr)_4av5#ny-#9&j9l=@xd2rz+7u*che9u%1%o*sa=4fz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
   # 'channels',  # khsha tkoun hia lowla

    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'main_app',
    'dashboard',
    'SocialMedia',
    'journal',
    'ecommerce',
    'qa',
    'ao',
    'eLearning',

    'widget_tweaks',
    'imagekit',
    'ckeditor',
    'ckeditor_uploader',
    'captcha',
    'paypal.standard.ipn',
    'paypal.standard.pdt',
    'crispy_forms',
    'easy_select2',
    'django_select2',
    'rest_framework',
    'oauth2client',
    'googleapiclient',

    'django_user_agents',
    'tracking_analyzer',
    'django_social_share',

    'bs4',

    'pusher_chat_app',
    'jwt',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_user_agents.middleware.UserAgentMiddleware",
]

ROOT_URLCONF = 'SocialNetworkJob.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'journal.context_processors.global_var',
                'ecommerce.context_processors.global_var',
                'SocialMedia.context_processors.global_var',
                'SocialNetworkJob.context_processors.global_settings',
                'dashboard.context_processors.global_settings',
                'qa.context_processors.global_var',

                'ao.context_processors.global_var',

            ],
        },
    },
]

WSGI_APPLICATION = 'SocialNetworkJob.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Email Configuration
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'bebi.company@gmail.com'
EMAIL_HOST_PASSWORD = 'Alfa@@@123'
EMAIL_PORT = 587

# Authentication BackEnd
AUTHENTICATION_BACKENDS = ['main_app.backends.EmailBackend']

TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 1120,
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'modern',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
    }

RECAPTCHA_PROXY = 'http://127.0.0.1:8000'

os.environ['RECAPTCHA_TESTING'] = 'True'

#django-paypal settings
PAYPAL_RECEIVER_EMAIL = 'karimelkhaoua_espr@gmail.com'
PAYPAL_TEST = True

PAYPAL_IDENTITY_TOKEN = "access_token$sandbox$j38xs6r3b4gg79ng$ac605fc10d86a52d176d6064dd28d333"

NOCAPTCHA = True


CRISPY_TEMPLATE_PACK = 'bootstrap3'

MARKDOWNX_EDITOR_RESIZABLE = True

LOGIN_REDIRECT_URL = '/login'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
        "width": '100%',
    },
}

LANGUAGES = [
#    ('de', _('German')),
   ('en', ('English')),
   ('fr', ('French')),
#    ('es', _('Spanish')),
#    ('pt', _('Portuguese'))
]


LOCALE_PATHS = (
    os.path.join(BASE_DIR , 'locale'),
)

MARKDOWN_EDITOR_SKIN = 'simple'

CKEDITOR_UPLOAD_PATH = "uploads/"



#Recaptcha

GOOGLE_RECAPTCHA_SECRET_KEY = '6LcIOV8UAAAAAGNiz4ZWD-Hz4EPZwdHOVLndj-xc'


#Google Analytics

GOOGLE_ANALYTICS = {
    'GOOGLE_ANALYTICS_ID': 'UA-125193151-1',
}

# django-analytics-tracker


GEOIP_PATH = 'dashboard/geoip_dataset/'


# Pusher chatkit settings

PUSHER_INSTANCE_LOCATOR = "v1:us1:f43a92eb-92eb-4bf6-978b-caf1efff74b9"
PUSHER_SECRET_KEY = "bcebc7cc-2137-42a7-98ab-006924e2edf1:6RZaUUWVybIMcWG0IGqrlKf/ZCwk7cYzUV90bYUVVQM="
PUSHER_INSTANCE_ID = PUSHER_INSTANCE_LOCATOR.split(":")[2]
PUSHER_KEY_ID = PUSHER_SECRET_KEY.split(":")[0]
PUSHER_SECRET = PUSHER_SECRET_KEY.split(":")[1]
PUSHER_CHATKIT_SUPERADMIN_ID = "ecosysteme_btp_superadmin"

# Share Facebook MEssenger

FACEBOOK_APP_ID = "274585039913237"