# Generated by Django 2.0.6 on 2018-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_analyzer', '0002_auto_20160719_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='model_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
